### ISSUE TITLE
Error with running Setup.py

### ISSUE THREAD

**Issue by heatherdefunk** [RyanMaugin/Tachyon#5]
In terminal, I entered `python setup.py` and I got the error `File "setup.py", line 22
SyntaxError: Non-ASCII character '\xe2' in file setup.py on line 22, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`.
I cloned Tachyon into Library with git clone `https://github.com/RyanMaugin/Tachyon.git Tachyon` as told, btw.

**Comment by RyanMaugin** [comment]
Accepted your commit and that should of solved it now :)

**Comment by ThatOneCalculator** [comment]
When one forgets square root ain't unicode
